============================= test session starts ==============================
platform linux -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
Using --random-order-bucket=global
Using --random-order-seed=21360

rootdir: /sandbox
plugins: cov-2.11.1, mock-3.5.1, random-order-1.0.4
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
______________________ ERROR collecting test_fizz_buzz.py ______________________
In test_fizz_buzz: function uses no argument 'test_input'
=========================== short test summary info ============================
ERROR test_fizz_buzz.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.18s ===============================
